### ISSUE TITLE
CA not working in MacBook

### ISSUE THREAD

**Issue by Chakazul** [distillpub/post--growing-ca#6]
My MacBook (both Chrome and Safari) shows the simulation with the following slowly growing lump. It's OK in my PC notebook.

<img width="668" alt="Screen Shot 2020-02-19 at 3 45 42 PM" src="https://user-images.githubusercontent.com/36795411/74812741-0921cd80-532f-11ea-98ff-0b44c38de3cf.png">
<img width="667" alt="Screen Shot 2020-02-19 at 3 46 05 PM" src="https://user-images.githubusercontent.com/36795411/74812745-0aeb9100-532f-11ea-84bf-bdc22712d15c.png">

**Comment by znah** [comment]
Hmm, this is strange... All MacBooks I've tried (incl Air 2014 and Pro 2012) worked fine. Which MacBook is it and what's the GPU?

**Comment by Chakazul** [comment]
OK now after rebooting.
It's MacBook Pro with 2 built-in GPUs (Intel Iris Pro and AMD Radeon R9). Guess I messed up the GPU when trying to get Lenia run faster.

BTW the kids love NeuroCA 😃

**Comment by Ashkenazic** [comment]
Try cross platform compiler.
